title: dinghy.dev
tagline: Diagram and Infrastructure as Code with React
url: https://docs.dinghy.dev
# baseUrl: /
baseUrl: /preview/
favicon: /assets/img/favicon.ico
docs:
  editUrl: https://github.com/dinghydev/dinghy/blob/main/sites/www/
  # Cannot show git info due to files been mounted from outside of the site folder
  # showLastUpdateAuthor: true
  # showLastUpdateTime: true
themeConfig:
  metadata:
    - name: keywords
      content: dinghy, diagram as code, infrastructure as code, react
  navbar:
    # title: dinghy.dev
    logo:
      alt: Logo
      src: /assets/img/logo.svg
    items:
      # - type: docSidebar
      #   sidebarId: gettingStartedSidebar
      #   position: left
      #   label: Getting Started
      - to: /get-started
        label: Get Started
        position: left
      # - href: /references/
      #   label: References
      #   position: left
      # - to: /examples
      #   label: Examples
      #   position: left
      - to: /community
        label: Community
        position: left
      - to: /contact
        label: Contact
        position: left
      - href: https://github.com/dinghydev/dinghy
        position: right
        className: header-github-link
        aria-label: GitHub repository
  footer: false
deploy:
  s3Url: s3://dinghy-website-play-v1
