docs:
  editUrl: https://github.com/dinghydev/dinghy/blob/main/sites/www/
themeConfig:
  navbar:
    items:
      - to: /guides
        label: Guides
        position: left
      - to: /examples
        label: Examples
        position: left
      - to: /references
        label: References
        position: left
      - to: /community
        label: Community
        position: left
      - href: https://github.com/dinghydev/dinghy
        position: right
        className: header-github-link
        aria-label: GitHub repository
