site:
  deploy:
    s3Url: s3://dinghy-dev-site-www
  volumes:
    - ../www/static:static
    - ../www/src/components:src/components
    - ../www/src/css:src/css
    - ../www/src/theme:src/theme
baseUrl: /references/diagrams/
docs:
  routeBasePath: /
  editUrl: https://github.com/dinghydev/dinghy/blob/main/sites/references-diagrams/
themeConfig:
  navbar:
    logo:
      href: https://dinghy.dev/
      target: _self
    items:
      - href: https://dinghy.dev/guides
        html: Guides
        target: _self
        position: left
      - href: https://dinghy.dev/examples
        html: Examples
        target: _self
        position: left
      - href: https://dinghy.dev/references
        html: References
        target: _self
        className: navbar__link--active
        position: left
      - href: https://dinghy.dev/community
        html: Community
        position: left
        target: _self
      - href: https://github.com/dinghydev/dinghy
        position: right
        className: header-github-link
        aria-label: GitHub repository
