# s3Backend:
#   bucket: my-unique-s3-bucket-name
# awsProvider:
#   region: eu-west-1
# ec2Servers:
#   my-server:
#     instance_type: t4.nano # default is t4g.nano which is arm64 architecture
#     linuxFlavor: ubuntu # default is al2023 which is amazon linux 2023
#     root_block_device:
#       volume_size: 100 # default is 8GB
