site:
  deploy:
    s3Url: s3://dinghy-dev-site-www
    s3Region: eu-west-1
title: dinghy.dev
tagline: Diagram and Infrastructure as Code with React
url: https://dinghy.dev
favicon: /assets/img/favicon.ico
themeConfig:
  metadata:
    - name: keywords
      content: dinghy, diagram as code, infrastructure as code, react
  navbar:
    title: Dinghy
    logo:
      alt: Logo
      src: /assets/img/logo.svg
      href: /
  footer:
    copyright: Â© YYYY <a href="https://dinghy.dev">dinghy.dev</a>
  algolia:
    appId: NFDOJ9SF91
    apiKey: 75e2f9fc53ca9b901a6d04a36561f8b6
    indexName: www
    # // Optional: see doc section below
    contextualSearch: true
    # // Optional: Specify domains where the navigation should occur through window.location instead on history.push. Useful when our Algolia config crawls multiple documentation sites and we want to navigate with window.location.href to them.
    # externalUrlRegex: "/diagrams/elements/"
    # // Optional: Algolia search parameters
    # searchParameters: {},
    # // Optional: path for search page that enabled by default (`false` to disable it)
    # searchPagePath: 'search',
    # // Optional: whether the insights feature is enabled or not on Docsearch (`false` by default)
    insights: true
    # // Optional: whether you want to use the new Ask AI feature (undefined by default)
    # askAi: 'YOUR_ALGOLIA_ASK_AI_ASSISTANT_ID',
